### PR TITLE
Exception on scrolling since 11.9.1

### PR DESCRIPTION
**Pull request by Alexander-Ploskin**
MFXScrollBar throws an exception when VirtualScrollPane.isAutoHideBars is true since 11.9.1. I think it is related to MFXEffects, but I have no idea how to fix it.

### CODE REVIEW

**Comment by palexdev** [comment]
What exception can you post the stacktrace?
I cannot test it right now but I may tell you why looking at the exception

**Comment by Alexander-Ploskin** [comment]
`java.lang.IllegalArgumentException: Cannot register this When construct as the given observable is already being observed
	io.github.palexdev.mfxcore.observables.When.register(When.java:108)
	io.github.palexdev.mfxcore.observables.OnChanged.listen(OnChanged.java:192)
	io.github.palexdev.mfxcore.observables.OnChanged.listen(OnChanged.java:59)
	io.github.palexdev.virtualizedfx.controls.skins.VirtualScrollPaneSkin.lambda$addListeners$19(VirtualScrollPaneSkin.java:355)
	com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:78)
	javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
	javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	javafx.scene.Node.setHover(Node.java:7244)
	javafx.scene.Node.preprocessMouseEvent(Node.java:8495)
	javafx.scene.Node.lambda$buildEventDispatchChain$3(Node.java:8857)
	com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	javafx.event.Event.fireEvent(Event.java:198)
	com.sun.javafx.event.EventQueue.fire(EventQueue.java:48)
	javafx.scene.Scene$MouseHandler.handleEnterExit(Scene.java:3808)
	javafx.scene.Scene$MouseHandler.process(Scene.java:3879)
	javafx.scene.Scene.processMouseEvent(Scene.java:1887)
	javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2620)
	com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	com.sun.glass.ui.View.notifyMouse(View.java:937)
	com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)`

**Comment by palexdev** [comment]
@Alexander-Ploskin Yes this is a known issue: [Discussion](https://github.com/palexdev/MaterialFX/discussions/307#discussioncomment-5563352)
The fix is ready on the MFXCore side, need to push and then update VirtualizedFX

**Comment by Alexander-Ploskin** [comment]
Thank you, waiting for the fix.

**Comment by palexdev** [comment]
Fixed in latest release

**Pull request closed without merging**
